---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: mongoredis
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        env:
          - name: REDIS_HOST
            value: root
          - name: REDIS_PORT
            value: '6379'
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-persistent-storage
            mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
---          
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: mongoredis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis-port-6379 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: mongoredis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hcloud-volumes