apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: default
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Password
        - name: MYSQL_DATABASE
          value: posts
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /opt/mysql/data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---          
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 3306  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hcloud-volumes