apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: webgatos
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webgatos
  minReplicas: {{ .Values.webgatos.hpa.minReplicas }}
  maxReplicas: {{ .Values.webgatos.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.webgatos.hpa.targetAverageUtilization }}
      