apiVersion: v1
kind: Service
metadata:
  name: webgatos-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: webgatos
spec:
  ports:
    - port: {{ .Values.webgatos.service.port }}
      targetPort: {{ .Values.webgatos.service.targetPort }}
      protocol: TCP
      name: webgatos-port
  selector:
    app: webgatos
  type: {{ .Values.webgatos.service.type }}
  