apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: mysql-standalone
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: java
        image: huertaslopez/webmysqlstandalone:v1.0
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db/anuncios
        - name: DATABASE_HOST
          value: db
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: mysql-standalone
  labels:
    app: webapp
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 8080
    targetPort: 8080